# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Loop3DModelGenDockWidget
								 A QGIS plugin
 This plugin preprocess map layers using map2loop and use its output for 3D modelling using LoopStructural.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
							 -------------------
		begin                : 2024-12-13
		git sha              : $Format:%H$
		copyright            : (C) 2024 by Center of Exploration Targeting, UWA
		email                : michel.nzikoumamboukou@uwa.edu.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""



from PyQt5.QtWidgets import QWidget, QComboBox, QLineEdit

class GeologyFaultStructureComboBoxes:
	def get_combo_boxes_and_param_boxes(self):

		def get_widgets(prefix, count):
			return [getattr(self, f"{prefix}_{i}") for i in range(1, count + 1)]

		return {
			"geology_combo_boxes": get_widgets("geology_field_comboBox", 10),
			"geology_param_boxes": [
				self.geology_plutondip_QLineEdit,
				self.geology_plutonform_comboBox,
				self.geology_intrusionmode_comboBox,
				self.geology_maxthickness_QLineEdit,
				self.geology_thicknessbuffer_QLineEdit,
				self.geology_contactDecimate_QLineEdit,
				self.geology_contactdip_QLineEdit,
				self.geology_contactorientationdecimate_QLineEdit,
				self.geology_misorientation_QLineEdit,
			],
			"fault_combo_boxes": get_widgets("fault_field_comboBox", 7),
			"fault_param_boxes": [
				self.fault_defaultdip_QLineEdit,
				self.fault_decimation_QLineEdit,
				self.fault_minlen_QLineEdit,
			],
			"struct_combo_boxes": get_widgets("struct_field_comboBox", 6),
			"struct_param_boxes": [
				self.struct_misorientation_QLineEdit,
				self.struct_decimation_QLineEdit,
			]
		}

	# s
