# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Loop3DModelGenDockWidget
								 A QGIS plugin
 This plugin preprocess map layers using map2loop and use its output for 3D modelling using LoopStructural.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
							 -------------------
		begin                : 2024-12-13
		git sha              : $Format:%H$
		copyright            : (C) 2024 by Center of Exploration Targeting, UWA
		email                : michel.nzikoumamboukou@uwa.edu.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
#from PyQt5.QtWidgets import QWidget
from .load_qt_features import GeologyFaultStructureComboBoxes


def force_clear_combo_box(combo_box):
	"""Forcefully remove all items from a QComboBox if it is not already empty."""
	if combo_box.count() == 0:
		print(f"Skipped clearing {combo_box.objectName()} (already empty).")
		return

	combo_box.clear()  # Clear only if it contains items
	print(f"Cleared {combo_box.objectName()} ✅")
	

def reset_category(self, category):
	"""Clear all UI elements (combo boxes and parameter boxes) for a specific category"""
	# Fetch combo boxes and parameter boxes
	boxes = GeologyFaultStructureComboBoxes.get_combo_boxes_and_param_boxes(self)

	# Assign unique combo boxes and parameter boxes to avoid duplicates
	self.geology_combo_boxes = list(set(boxes.get("geology_combo_boxes", []) + [self.geology_Qgis_comboBox]))
	self.geology_param_boxes = list(set(boxes.get("geology_param_boxes", []) + [self.geology_sill_QLineEdit, self.geology_intrusion_QLineEdit, self.geology_QLineEdit]))
	self.fault_combo_boxes = list(set(boxes.get("fault_combo_boxes", []) + [self.fault_Qgis_comboBox]))
	self.fault_param_boxes = list(set(boxes.get("fault_param_boxes", []) + [self.fault_ftext_QLineEdit, self.fault_fdipest_QLineEdit, self.fault_QLineEdit]))
	self.struct_combo_boxes = list(set(boxes.get("struct_combo_boxes", []) + [self.struct_Qgis_comboBox]))
	self.struct_param_boxes = list(set(boxes.get("struct_param_boxes", []) + [self.struct_bedding_QLineEdit, self.struct_overturned_QLineEdit, self.struct_QLineEdit]))

	print(f"Running reset for {category}")

	# Clear all combo boxes
	combo_boxes_attr = f"{category}_combo_boxes"
	if hasattr(self, combo_boxes_attr):
		combo_boxes = getattr(self, combo_boxes_attr)
		for combo_box in combo_boxes:
			force_clear_combo_box(combo_box)

	# Explicitly clear main QGIS combo boxes only if needed
	explicit_boxes = {
		"geology": self.geology_Qgis_comboBox,
		"fault": self.fault_Qgis_comboBox,
		"struct": self.struct_Qgis_comboBox
	}
	
	if category in explicit_boxes and explicit_boxes[category] not in getattr(self, combo_boxes_attr, []):
		force_clear_combo_box(explicit_boxes[category])

	# Clear parameter boxes
	param_boxes_attr = f"{category}_param_boxes"
	if hasattr(self, param_boxes_attr):
		param_boxes = getattr(self, param_boxes_attr)
		for param_box in param_boxes:
			if hasattr(param_box, 'clear'):
				param_box.clear()
				print(f"Cleared {param_box.objectName()}")
			elif hasattr(param_box, 'setText'):
				param_box.setText("")
				print(f"Cleared text in {param_box.objectName()}")

	# Uncheck checkboxes
	checkbox_attr_map = {
		"geology": ["geology_Qgis_checkBox", "geology_json_checkBox"],
		"fault": ["fault_Qgis_checkBox", "fault_json_checkBox"],
		"struct": ["struct_Qgis_checkBox", "struct_json_checkBox"]
	}

	if category in checkbox_attr_map:
		for checkbox_attr in checkbox_attr_map[category]:
			if hasattr(self, checkbox_attr):
				checkbox = getattr(self, checkbox_attr)
				if checkbox.isChecked():
					checkbox.setChecked(False)
					print(f"Unchecked {checkbox.objectName()}")

	# Force UI update to reflect changes
	self.repaint()
	self.update()


