
# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Loop3DModelGenDockWidget
                                 A QGIS plugin
 This plugin preprocess map layers using map2loop and use its output for 3D modelling using LoopStructural.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-13
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Center of Exploration Targeting, UWA
        email                : michel.nzikoumamboukou@uwa.edu.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

# BASE_DIR = os.path.dirname(__file__)
# help_config_path = os.path.join(BASE_DIR, "help_config.json")

def assign_tooltips_to_ui_elements(self):
    """
    Populate text information when the mouse hovers over a button.
    """
    config_data = {
        "config_page": [
            [self.load_configdata_from_file_radioButton, "Click to select directory from which to load data from your computer"],
            [self.load_configdata_from_json_radioButton, "Click to load data using a pre-existing JSON file"],
            [self.CRS_QgsProjectionSelectionWidget, "CRS selection: Select the right CRS"],
            [self.CRS_pushButton_load_value, "Click to save your selected CRS value"],
            [self.CRS_lineEdit_value, "The selected CRS value will be displayed here"],
            [self.conf_QGIS_radioButton, "Click to load DTM from QGIS panel"],
            [self.conf_AUS_radioButton, "Click to load DTM from GA server"],
            [self.conf_JSON_radioButton, "Click to load DTM from your pre-existing JSON file"],
            [self.lineEdit_dtm_path, "Selected DTM path or server will be displayed here"],
            [self.Rawdata_radioButton, "Click to use loaded data from QGIS panel"],
            [self.clippeddata_radioButton, "Click if you want to clip your data"],
            [self.CreateROI_radioButton, "Click to create a region of interest (ROI)"],
            [self.ExistingROI_radioButton, "Click if you are willing to use existing ROI"],
            [self.save_roi, "Save your ROI if you are using CreateROI option"],
            [self.Ok_ClipLayer, "Click to clip all selected layers"],
            [self.conf_shp_tif_listWidget, "QWidgetList: Filled based on selected options"],
            [self.ResetConfiguration_pushButton, "Reset or reload all UI features on this page"],
            [self.conf_log_listWidget, "QWidgetList: Contains logs and instructions"],
        ],
        "config_geology": [
            [self.geology_Qgis_checkBox, "Click to load all geology layers from QGIS panel"],
            [self.geology_json_checkBox, "Click to load geology layer from a pre-existing JSON file"],
            [self.geology_Qgis_comboBox, "Select geology layer"],
            [self.geology_Ok_pushButton, "Click to save selected layer"],
            [self.geology_clear_pushButton, "Click to clear selected layer and features"],
            [self.geology_QLineEdit, "Geology file path will be displayed here"],
            [self.geology_field_comboBox_1, "Formation*: field that contains finer stratigraphic coding"],
            [self.geology_field_comboBox_2, "Group: field that contains coarser stratigraphic coding"],
            [self.geology_field_comboBox_3, "Supergroup: field that contains alternate coarser stratigraphic coding if <g> is blank."],
            [self.geology_field_comboBox_4, "Description: field that contains information about lithology."],
            [self.geology_field_comboBox_5, "FM code: field that contains alternate stratigraphic coding."],
            [self.geology_field_comboBox_6, "Rocktype 1: field that contains extra lithology information."],
            [self.geology_field_comboBox_7, "Rocktype 2: field that contains even more lithology information."],
            [self.geology_field_comboBox_8, "Polygon ID: object id."],
            [self.geology_field_comboBox_9, "Min Age: field that contains minimum age of unit defined by ccode."],
            [self.geology_field_comboBox_10, "Max Age: field that contains maximum age of unit defined by ccode."],
            [self.geology_sill_QLineEdit, "Sill: text to search for in field defined by ds code to show that this is a sill."],
            [self.geology_intrusion_QLineEdit, "Intrusion: text to search for in field defined by r1 code to show that this is an intrusion."],
            [self.geology_plutondip_QLineEdit, "pluton_dip (int)[45]: In degrees: default pluton contact dip."],
            [self.geology_plutonform_comboBox, "pluton_form(str)['domes']: Possible forms from domes, saucers or pendant."],
            [self.geology_intrusionmode_comboBox, "intrusion_mode(int): [1] to exclude all intrusions from basal contacts, [0] to only exclude sills."],
            [self.geology_maxthickness_QLineEdit, "max_thickness_allowed(int)[10000]: When estimating local formation thickness in metres."],
            [self.geology_thicknessbuffer_QLineEdit,  "thickness_buffer(int)[5000]: In metres: How far away to look for next highest unit when calculating formation thickness."],
            [self.geology_contactDecimate_QLineEdit, "contact_decimate(int)[5]: Save every nth contact data point. 0 means save all data."],
            [self.geology_contactdip_QLineEdit, "contact_dip(int)[-999]: In degrees: Dip to assign to all new basal contact orientations. If -999 then the nearest interpolated dip for that supergroup will be used instead."],
            [self.geology_contactorientationdecimate_QLineEdit, "contact_orientation_decimate(int)[5]: Save every nth contact orientation point. 0 means save all data."],
            [self.geology_misorientation_QLineEdit,  "misorientation(int)[30]: Maximum misorientation in pole to great circle of bedding between groups to be considered part of same supergroup."],
            [self.geology_log_listWidget,        '''QWidgetList:
            Filled with: 
            1- Instruction on how to run the geology tab. 
            2- Filled with all log actions taken on this page'''],
            [self.geology_tableWidget, "QWidgetTable: Filled with Layer Attribute tabel"],
        ],
        "config_fault": [
            [self.fault_Qgis_checkBox, "Click to load all fault layers from QGIS panel"],
            [self.fault_json_checkBox, "Click to load fault layer from a pre-existing JSON file"],
            [self.fault_Qgis_comboBox, "Select fault layer"],
            [self.fault_Ok_pushButton, "Click to save selected layer"],
            [self.fault_clear_pushButton, "Click to clear selected layer and features"],
            [self.fault_QLineEdit, "Fault file path will be displayed here"],
            [self.fault_field_comboBox_1, "Default Dip*: field for numeric fault dip value."],
            [self.fault_field_comboBox_2, "Dip Direction*: field for text fault dip direction value."],
            [self.fault_field_comboBox_3, "Feature*: field that contains information on type of structure."],
            [self.fault_field_comboBox_4, "Dip Diection type: field that contains type of foliation."],
            [self.fault_field_comboBox_5, "Fdipest: field for text fault dip estimate value."],
            [self.fault_field_comboBox_6, "Point ID: object id for structures."],
            [self.fault_field_comboBox_7, "Dip Direction Convention*: flag to determine measurement convention (currently <strike> or <dip direction>)."],
            [self.fault_ftext_QLineEdit,  "Fault flag: text to search for in field defined by f code to show that this is a fault"],
            [self.fault_fdipest_QLineEdit, "Fdipest flag: text to search for in field defined by fdipest to give fault dip estimate in increasing steepness"],
            [self.fault_defaultdip_QLineEdit, "Default fault dip in degrees. [90]"],
            [self.fault_decimation_QLineEdit, "Save every nth fault data point along fault trace. 0 means save all data. [5]"],
            [self.fault_minlen_QLineEdit, "Minimum fault length in meters to be considered. [5000]"],
            [self.fault_log_listWidget,         '''QWidgetList :
            Filled with:
            1- Instruction on how to run the fault tab.
            2- Filled with all log actions taken on this page'''],
        ],
        "config_structure": [
            [self.struct_Qgis_checkBox, "Click to load all structure point layers from QGIS panel"],
            [self.struct_json_checkBox, "Click to load structure point layer from a pre-existing JSON file"],
            [self.struct_Qgis_comboBox, "Select structure point layer"],
            [self.struct_Ok_pushButton, "Click to save selected layer"],
            [self.struct_clear_pushButton, "Click to clear selected layer and features"],
            [self.struct_QLineEdit, "Structure point file path will be displayed here"],
            [self.struct_field_comboBox_1, "Default Dip*: field that contains dip information."],
            [self.struct_field_comboBox_2, "Dip Direction*: field that contains dip direction information."],
            [self.struct_field_comboBox_3, "Feature*: field that contains information on type of structure."],
            [self.struct_field_comboBox_4, "Dip Direction Convention*: flag to determine measurement convention (currently <strike> or <dip direction>)."],
            [self.struct_field_comboBox_5, "field that contains information on type of structure."],
            [self.struct_field_comboBox_6, "Point ID: object id for structures."],
            [self.struct_bedding_QLineEdit, "Bedding flag: text to search for in field defined by sf code to show that this is a bedding measurement."],
            [self.struct_overturned_QLineEdit, "Overturned flag: text to search for in field defined by bo code to show that this is an overturned bedding measurement."],
            [self.struct_misorientation_QLineEdit, "Maximum misorientation in pole to great circle of bedding between groups to be considered part of same supergroup (int) [30]"],
            [self.struct_decimation_QLineEdit, "Save every nth orientation data point. 0 means save all data. (int) [0]"],
            [self.struct_log_listWidget,  '''QWidgetList :
            Filled with:
            1- Instruction on how to run the structure tab.
            2- Filled with all log actions taken on this page'''],
        ],
        "config_run": [
            [self.m2l_output_lineedit, "Map2Loop output folder, default is m2l_output"],
            [self.l2s_output_lineedit, "LoopStructural output folder, default is l2s_output"],
            [self.Run_Preprocessor_pushButton, "Click to save all config parameters and new shapefiles"],
            [self.Run_Map2loop_pushButton, "Click to run Map2Loop engine"],
            [self.Run_LoopStructural_pushButton, "Click to push data into modeling"],
            [self.Run_viz_pushButton, "Click to visualize the result as a 3D model"],
            [self.loop_qgis_pushButton, "Click to Run LoopStructural locally"],
            [self.loop_docker_pushButton, "Click to Run LoopStructural using docker"],
            [self.loop_gcp_pushButton, "Click to Run LoopStructural using Google Cloud Platform"],
            [self.loop_aws_pushButton, "Click to Run LoopStructural using AWS"],
            [self.regularisation_lineedit,  "Regularisation value"],
            [self.fault_nelts_lineedit, "Fault grid size value"],
            [self.foliation_nelts_lineedit, "Foliation grid size value"],
            [self.interpolator_comboBox, "Select the interpolation type"],
            [self.f_min_length_lineedit, "Minimun fault length value"],
            [self.g_sampler_lineedit, "Geology sampler spacing value"],
            [self.f_sampler_lineedit, "Fault sampler spacing value"],
            [self.sampler_decimator_lineedit,  "Sampler decimator value"],
            [self.base_lineedit, "Map base value"],
            [self.top_lineedit, "Map top value"],
            [self.minx_lineedit, "Map minimum x value"],
            [self.maxx_lineedit, "Map maximum x value"],
            [self.miny_lineedit, "Map minimum y value"],
            [self.maxy_lineedit, "Map maximum y value"],
            [self.run_log_listWidget,  '''QWidgetList :
            Filled with:
            1- Instruction on how to run the structure tab.
            2- Filled with all log actions taken on this page'''],
           

        ],
    }

    # Assign tooltips dynamically
    for category, elements in config_data.items():
        for widget, tooltip in elements:
            if widget is not None:
                widget.setToolTip(tooltip)
