# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Loop3DModelGenDockWidget
								 A QGIS plugin
 This plugin preprocess map layers using map2loop and use its output for 3D modelling using LoopStructural.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
							 -------------------
		begin                : 2024-12-13
		git sha              : $Format:%H$
		copyright            : (C) 2024 by Center of Exploration Targeting, UWA
		email                : michel.nzikoumamboukou@uwa.edu.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import subprocess,os
import pyvista as pv
from pyvistaqt import BackgroundPlotter
from pathlib import Path
from pyvistaqt import QtInteractor
from PyQt5.QtWidgets import (QApplication, QWidget, QVBoxLayout, QHBoxLayout, 
							QCheckBox, QGroupBox, QFrame, QLabel)
from PyQt5.QtCore import Qt


class VTKVisualizer(QWidget):
    def __init__(self, vtk_folder_path, parent=None):
        super().__init__(parent)
        self.vtk_folder_path = vtk_folder_path
        
        # Scan vtk files
        self.all_vtk_files = os.listdir(self.vtk_folder_path)
        self.full_paths = [os.path.join(vtk_folder_path, f) for f in self.all_vtk_files]
        
    def setup_plotter(self, widget):
        """Create a plotter directly inside the provided widget"""
        # Clear any existing layout and children
        if widget.layout():
            # Remove all items from layout
            while widget.layout().count():
                item = widget.layout().takeAt(0)
                if item.widget():
                    item.widget().deleteLater()
            # Remove the layout itself
            old_layout = widget.layout()
            QWidget().setLayout(old_layout)  # Transfer ownership
            
        # Create new layout
        layout = QVBoxLayout(widget)
        layout.setContentsMargins(0, 0, 0, 0)
        
        # Create the plotter
        self.plotter = QtInteractor(widget)
        layout.addWidget(self.plotter)
        
        return self.plotter
        
    def visualize(self, widget, title="3D Model"):
        """Set up the plotter and visualize data with title"""
        # Create plotter inside the provided widget
        plotter = self.setup_plotter(widget)
        
        # Now plot the data
        plotter.clear()
        
        # Add title to the visualization
        plotter.add_text(title, position="upper_edge", font_size=14, color="black", shadow=True)
        
        # Find and load files
        surfaces = [f for f in self.full_paths if "Fault" in f]
        stratigraphy = [f for f in self.full_paths if "sg" in f]
        block_model_path = next((f for f in self.full_paths if "block_model" in f), None)
        
        # Add a test object if no data is found (to verify rendering works)
        if not (surfaces or stratigraphy or block_model_path):
            test_mesh = pv.Sphere()
            plotter.add_mesh(test_mesh, color="red", name="Test Sphere")
            print("No VTK files found, displaying test sphere")
        
        # Create a legend entries list
        legend_entries = []
        
        # Add block model
        if block_model_path:
            try:
                mesh = pv.read(block_model_path)
                plotter.add_mesh(mesh, color="lightblue", opacity=0.7, name="Block Model")
                legend_entries.append(["Block Model", "lightblue"])
                print(f"Added block model: {block_model_path}")
            except Exception as e:
                print(f"Error loading block model: {e}")
        
        # Add surfaces
        for i, s in enumerate(surfaces):
            try:
                mesh = pv.read(s)
                # Extract the fault name from the filename
                fault_name = os.path.basename(s).replace(".vtk", "")
                plotter.add_mesh(mesh, color="green", opacity=0.6, name=fault_name)
                if i == 0:  # Add only one entry for all faults to avoid clutter
                    legend_entries.append(["Faults", "green"])
                print(f"Added surface: {s}")
            except Exception as e:
                print(f"Error loading surface {s}: {e}")
        
        # Add stratigraphy
        for i, s in enumerate(stratigraphy):
            try:
                mesh = pv.read(s)
                # Extract the stratigraphy name from the filename
                strat_name = os.path.basename(s).replace(".vtk", "")
                plotter.add_mesh(mesh, color="brown", opacity=0.8, name=strat_name)
                if i == 0:  # Add only one entry for all stratigraphy to avoid clutter
                    legend_entries.append(["Stratigraphy", "brown"])
                print(f"Added stratigraphy: {s}")
            except Exception as e:
                print(f"Error loading stratigraphy {s}: {e}")
        
        # Add the legend if we have entries
        if legend_entries:
            plotter.add_legend(legend_entries, bcolor="white", border=True, size=(0.15, 0.15), 
                              loc="upper right", face="circle")
            print("Added legend with entries:", legend_entries)
        
        # Ensure camera is set properly
        plotter.reset_camera()
        plotter.set_background("white")
        
        # Force update and rendering
        plotter.update()
        plotter.render()
        widget.update()
        
        print(f"Visualization completed with title '{title}' and legend")
        return plotter

    def update_color_scheme(self, plotter, block_color="lightblue", fault_color="green", strat_color="brown"):
        """Update the color scheme of the visualization and refresh the legend"""
        # Update block model color
        for actor in plotter.renderer.GetActors():
            prop = actor.GetProperty()
            if actor.GetObjectName() == "Block Model":
                prop.SetColor(*pv.parse_color(block_color))
                
        # Update fault colors
        for actor in plotter.renderer.GetActors():
            prop = actor.GetProperty()
            if "Fault" in actor.GetObjectName():
                prop.SetColor(*pv.parse_color(fault_color))
                
        # Update stratigraphy colors
        for actor in plotter.renderer.GetActors():
            prop = actor.GetProperty()
            if "sg" in actor.GetObjectName():
                prop.SetColor(*pv.parse_color(strat_color))
        
        # Update legend
        legend_entries = [
            ["Block Model", block_color],
            ["Faults", fault_color],
            ["Stratigraphy", strat_color]
        ]
        
        # Remove old legend and add updated one
        plotter.remove_legend()
        plotter.add_legend(legend_entries, bcolor="white", border=True, size=(0.15, 0.15),
                          loc="upper right", face="circle")
        
        # Render the updated scene
        plotter.render()
        print("Updated color scheme and legend")

# Example of how to use this in your main application:
"""
# In your main application:
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys

class MainApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()  # Your UI setup method
        
        # Assuming run_log_listWidget is already created
        
        # Create the visualizer
        vtk_folder = "/path/to/vtk/files"
        self.visualizer = VTKVisualizer(vtk_folder)
        
        # Visualize directly in the run_log_listWidget with title
        self.plotter = self.visualizer.visualize(self.run_log_listWidget, title="3D Geological Model")

if __name__ == "__main__":
    app = QApplication(sys.argv)
    main = MainApp()
    main.show()
    sys.exit(app.exec_())
"""