# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Loop3DModelGenDockWidget
								 A QGIS plugin
 This plugin preprocess map layers using map2loop and use its output for 3D modelling using LoopStructural.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
							 -------------------
		begin                : 2024-12-13
		git sha              : $Format:%H$
		copyright            : (C) 2024 by Center of Exploration Targeting, UWA
		email                : michel.nzikoumamboukou@uwa.edu.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


#!/usr/bin/env python
# coding: utf-8

# # Loop Workflow Example 3

# * High level approach to making a 3D model from just a bounding box and source files as input. (In Australia only for now. Documentation to come)
# This is the wrapper module to pass data and execute calculation in your container
from map2loop.project import Project
from map2loop.m2l_enums import Datatype, VerboseLevel
from map2loop.sampler import SamplerSpacing, SamplerDecimator
from map2loop.sorter import SorterAlpha
from map2loop.thickness_calculator import InterpolatedStructure, ThicknessCalculator
import time
import os, ast
import json
from pathlib import Path

##

from datetime import datetime


def save_mapdata_to_files(self, save_path: str = ".", extension: str = ".shp.zip"):
        """
        Saves the map data frames to csv files

        Args:
            save_path (str, optional):
                The path to save the file to. Defaults to ".".
            extension (str, optional):
                An alternate extension to save the GeoDataFrame in. Defaults to ".csv".
        """
        if not os.path.exists(save_path):
            os.mkdir(save_path)
        self.map_data.save_all_map_data(save_path, extension)


def save_all_map_data(self, output_dir: pathlib.Path, extension: str = ".csv"):
    """
    Save all the map data to file

    Args:
        output_dir (str):
            The directory to save to
        extension (str, optional):
            The extension to use for the data. Defaults to ".csv".
    """
    for i in [Datatype.GEOLOGY, Datatype.STRUCTURE, Datatype.FAULT, Datatype.FOLD]:
        self.save_raw_map_data(output_dir, i, extension)


def save_raw_map_data(
    self, output_dir: pathlib.Path, datatype: Datatype, extension: str = ".shp.zip"
):
    """
    Save the map data from datatype to file

    Args:
        output_dir (pathlib.Path):
            The directory to save to
        datatype (Datatype):
            The datatype of the geopanda to save
        extension (str, optional):
            The extension to use for the data. Defaults to ".csv".
    """
    try:
        filename = pathlib.Path(output_dir) / f"{datatype.name}{extension}"
        raw_data = self.raw_data[datatype]

        if raw_data is None:
            logger.info(f"No data available for {datatype.name}. Skipping saving to file {filename}.")
            return

        if extension == ".csv":
            raw_data.to_csv(filename, index=False)  # Save as CSV
        else:
            self.raw_data[datatype].to_file(filename)

    except Exception as e:
        logger.error(f"Failed to save {datatype.name} to file named {filename}\nError: {str(e)}")
        print(f"Failed to save {datatype.name} to file named {filename}\nError: {str(e)}")
